# Generated by Django 2.0.6 on 2018-06-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='content',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
