# Generated by Django 2.0.6 on 2018-06-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='user',
        ),
        migrations.DeleteModel(
            name='Input',
        ),
    ]
