# Generated by Django 2.0.6 on 2018-06-17 17:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20180611_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
