# Generated by Django 2.0.6 on 2018-06-18 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20180618_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='route',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='routes.Route'),
        ),
    ]
