# Generated by Django 2.0.6 on 2018-06-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_destination_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='step',
            field=models.IntegerField(default=1),
        ),
    ]
