# Generated by Django 2.0.6 on 2018-06-25 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_destination_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='route',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.Route'),
        ),
    ]
