# Generated by Django 2.0.6 on 2018-07-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_destination_is_removeable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['step']},
        ),
    ]
