# Generated by Django 2.0.6 on 2018-07-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0006_auto_20180718_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['created_at']},
        ),
    ]
